apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: my-release
      meta.helm.sh/release-namespace: nginx
    creationTimestamp: "2024-01-21T09:37:27Z"
    labels:
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: nginx
      app.kubernetes.io/version: 1.25.3
      helm.sh/chart: nginx-15.9.0
    name: my-release-nginx
    namespace: nginx
    resourceVersion: "205667"
    uid: b73c3f06-6d5a-4b06-a770-1f87d5cfd6d1
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.100.16.92
    clusterIPs:
    - 10.100.16.92
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 31038
      port: 80
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/name: nginx
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-01-21T09:41:31Z"
    labels:
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: nginx
      app.kubernetes.io/version: 1.25.3
      helm.sh/chart: nginx-15.9.0
    name: my-release-nginx-ext
    namespace: nginx
    resourceVersion: "208121"
    uid: 99262adf-4225-4fc8-8920-dcb16a201783
  spec:
    clusterIP: 10.103.162.167
    clusterIPs:
    - 10.103.162.167
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30443
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/name: nginx
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
